In [14]:
import numpy
#一，场景颜色提取
  #根据输入的场景图片提取主色调

#01 提取封面图像RGB
def getRGB_Photo(photo="scene"):
    #读取图片 B，G，R，返回多维矩阵h
    print("--01 正在提取照片RGB数据")
    Hrgb=100
    return Hrgb


#02 提取照片主色调
def extract_main_color(Hrgb):
    import random
    #根据照片颜色数据提取主色调，返回主色调的RGB值
    print("--02 正在计算照片主色调")
    Mcolor=numpy.array([random.randint(51,255),random.randint(51,255),random.randint(51,255)])
    return Mcolor



#二，计算主要颜色与次要颜色
  #定义服装的主要与次要配色
    
#03 计算照片主色调的补色
def compute_complementary_colour_of_main_color(Mcolor):
    print("--03 正在计算主色调补色")
    cC = Mcolor-50
    return cC

#04 根据计算结果在服装类颜色库中选取最接近的颜色，作为主要颜色
def select_similar_color_in_ClothingDatabase(cC):
    print("--04 正在于服装类颜色库中选取最接近的颜色")
    Acolor = cC + 1
    return Acolor

#05 根据色彩搭配规则计算与主要颜色搭配的次要颜色
def define_another_color(Acolor):
    print("--05 正在计算与主要颜色搭配的次要颜色")
    Bcolor = Acolor + 10
    return Bcolor    
    
    
#三，计算点缀颜色
  #定义鞋包等配饰的配色
    
#06 根据照片主色与服装主要颜色计算与二者相差最大的颜色
def compute_most_different_color(Mcolor,Acolor):
    print("--06 正在计算点缀颜色")
    dC = Mcolor+Acolor-50
    return dC 

#07 根据计算结果在配饰类颜色库中选取最接近的颜色，作为点缀颜色
def select_similar_color_in_AccaccessoryDatabase(dC):
    print("--07 正在选取点缀颜色")
    Ccolor = dC + 1
    return Ccolor



Hrgb=getRGB_Photo("scene1")
Mcolor=extract_main_color(Hrgb)
cC=compute_complementary_colour_of_main_color(Mcolor)
Acolor=select_similar_color_in_ClothingDatabase(cC)
Bcolor=define_another_color(Acolor)
dC=compute_most_different_color(Mcolor,Acolor)
Ccolor=select_similar_color_in_AccaccessoryDatabase(dC)

print ("图片主色调为：")
print (Mcolor)
print ("服装主颜色为：")
print (Acolor)
print ("服装次颜色为：")
print (Bcolor)
print ("配饰颜色为：")
print (Ccolor)


--01 正在提取照片RGB数据
--02 正在计算照片主色调
--03 正在计算主色调补色
--04 正在于服装类颜色库中选取最接近的颜色
--05 正在计算与主要颜色搭配的次要颜色
--06 正在计算点缀颜色
--07 正在选取点缀颜色
图片主色调为：
[121  74 153]
服装主颜色为：
[ 72  25 104]
服装次颜色为：
[ 82  35 114]
配饰颜色为：
[144  50 208]
